### ISSUE TITLE
Ion identification within a mass spectrum

### ISSUE THREAD

**Issue by polklin** [nf-core/mhcquant#220]
Hello !

I am very new to MS/MS and MHCquant. 
I would like to get the peak identification in my mass spectrum when I visualize them, to know which peaks were considered as significant for peptide identification and which ion corresponds to which peak (cf image). 
I guess there is something within the pipeline that identifies such peaks: is there a way to retrieve this information somewhere ?

For now, I just retrieve the scan ID for each identified peptide, and I visualize the associated mass spectrum on XCalibur.

Best,
Paul

![image](https://user-images.githubusercontent.com/25035705/173079417-680ee4e1-7849-45a6-bb63-fa2e01798a13.png)

**Comment by timosachsenberg** [comment]
hi MHCquant performs the peptide assignments using a peptide identification engine. Unfortunately, it does not output the internal fragment annotations.
It would be possible to add this functionality to MHCquant using e.g., a pyOpenMS script.
https://pyopenms.readthedocs.io/en/latest/spectrumalignment.html gives some pointers how such a script could be written.
So if you feel fond of adding this functionality, I am happy to assist if questions arise. Otherwise, we can keep this issue as a feature request and hope that one of the developers pick it up.

**Comment by marissaDubbelaar** [comment]
Hey @polklin,
Good suggestion and @timosachsenberg thank you for the suggestion.
If possible, we could meet up during the next hackathon to work on this matter. 
Looking forward to implementing this with somebody.
