### ISSUE TITLE
protein fasta file with empty first line

### ISSUE THREAD

**Issue by praveenbas** [nf-core/mhcquant#78]
ERROR ~ Error executing process > 'generate_decoy_database (1)'

Caused by:
  Process `generate_decoy_database (1)` terminated with an error exit status (3)

Command executed:

  DecoyDatabase  -in UP000005640_9606_reviewed_added_vcf.fasta \
                 -out UP000005640_9606_reviewed_added_vcf_decoy.fasta \
                 -decoy_string DECOY_ \
                 -decoy_string_position prefix

Command exit status:
  3

Command output:
  Version 2.4.0-HEAD-2018-10-26 of DecoyDatabase is available at www.OpenMS.de
  Warning: Only one FASTA input file was provided, which might not contain contaminants.You probably want to have them! Just add the contaminant file to the input file list 'in'.
  Error: Unable to read file (Error while parsing FASTA file! The first entry could not be read! Please check the file! in: )

Command wrapper:
  Version 2.4.0-HEAD-2018-10-26 of DecoyDatabase is available at www.OpenMS.de
  Warning: Only one FASTA input file was provided, which might not contain contaminants.You probably want to have them! Just add the contaminant file to the input file list 'in'.
  Error: Unable to read file (Error while parsing FASTA file! The first entry could not be read! Please check the file! in: )

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

**Comment by Leon-Bichmann** [comment]
Thank you for opening this issue.

We now added the information to the troubleshooting, that there should be no empty lines in your fasta database.

**Comment by praveenbas** [comment]
Dear Leon, 
I guess the empty line was generated by the " generate_proteins_from_vcf" step because I double-checked and found no empty lines in the input VCF and reference fasta.

**Comment by Leon-Bichmann** [comment]
hmm... ok did it run through anyway in the end?

**Comment by praveenbas** [comment]
no.. it stopped at the "generate_decoy _database" step. 

However, when I manually removed the empty line from the "UP000005640_9606_reviewed_added_vcf.fasta" and restarted the workflow with "-resume", then it runs through successfully till the end.

**Comment by Leon-Bichmann** [comment]
ok can you send me the input files, I will have a look.

**Comment by JoBBurt** [comment]
Error executing process > 'generate_decoy_database (1)'

Caused by:
  Process `generate_decoy_database (1)` terminated with an error exit status (3)

Command executed:

  DecoyDatabase  -in Hops_HopBase_v5_maskedCascadePrimary_repeatsRemoved.cds.fasta \
              -out Hops_HopBase_v5_maskedCascadePrimary_repeatsRemoved.cds_decoy.fasta \
              -decoy_string DECOY_ \
              -decoy_string_position prefix \
              > Hops_HopBase_v5_maskedCascadePrimary_repeatsRemoved.cds_decoy_database.log

Command exit status:
  3

Command output:
  (empty)

Work dir:
  /wsu/home/gb/gb35/gb3520/work/94/554d8e4df2dc954f5637e186c969e4

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 When I check the log file I get this:

Error: Unable to read file (Cannot convert string to amino acid sequence: unexpected character 'a' in: atgaccctagaagctcatccaccacctcctcacaacccttcacatgtcctgcaggtcgtccaagtcgagccccaattaccacgatcccaggccatagaggcgagaccctcagcgaccatcctcgactctgtgttggggatgactatgacttcttgcatggctcagatccatactattgctcagatccaagctgaggtggatgaggccaggactgctttgggggaggtgaaggtcaccttggaggaggccaatgccatgaagtatgccctggacaaggccaaaaatgcccttaagacctcccacgcgaatgagaaaattgccaaaacacaagtcttgaagaaccaggaaggggatttatcattcctagacgaggaactttgggggcgctacctcaccatgtttcaagaccgattatcaaaagagtcggcgaagacagtggagacttcaagagctgtagcagaaggcagggaggaagaggtatcatcttga)

**Comment by Leon-Bichmann** [comment]
Hey in this case it is complaining that you are using a DNA sequence. Your database should only contain protein sequences. (Capital letter canonical Aminoacids)

**Comment by JoBBurt** [comment]
Whoops, thank you!
